node{
    withDockerContainer(image: 'python:2-alpine'){
        stage("Build"){
            sh 'python -m py_compile sources/add2vals.py sources/calc.py'
            stash(name: 'compiled-results', includes: 'sources/*.py*')
        }
    }
    withDockerContainer(image: 'qnib/pytest'){
        try{
            stage("Test"){
                sh 'py.test --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
            }
        } catch (e){
            sh "exit 1"
        } finally {
            junit 'test-reports/results.xml'
        }
    }
    withEnv(["VOL=$pwd/sources:/src", "IMAGE=cdrx/pyinstaller-linux:python2"]){
        try{
            stage("Deploy"){
                dir(path: env.BUILD_ID){
                    unstash(name: 'compiled-results')
                    sh "docker run --rm -v $VOL $IMAGE 'pyinstaller -F add2vals.py'"
                }
            }
        } catch(e){
            println "Failed because of $e"
        } finally {
            archiveArtifacts("$env.BUILD_ID/sources/dist/add2vals")
            sh "docker run --rm -v $VOL} $IMAGE 'rm -rf build dist'"
        }
    }
}